version: '3'
services:
  node:
    image: .
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
  mongo:
    image: mongo:3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /database/mongo