version: '2'
services:
  node:
    build: .
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - '/database/mongo:/data/db'